ASCIIdoctrine
=============
Benjamin Kober <benko@kober-systems.com>
:toc: left
// In diesem Dokument wird der ganze Quelltext angezeigt.
:code:

Eine asciidoc Implementierung in rust.

ASCIIdoctrine will möglichst kompatibel zur asciidoc Interpretation von http://asciidoctor.org[asciidoctor] sein, so dass es als Drop-in Ersatz genutzt werden kann. Allerdings ist es in https://www.rust-lang.org/[rust] geschrieben und hat das Ziel flexibeler und leichter zu portieren zu sein.

== Einstieg
Je nach Interessenlage und Beweggrund zum lesen dieses Artikels wird man
unterschiedlich an ihn herangehen.

[cols="a,a"]
|===
|
Einstieg & Tutorials
~~~~~~~~~~~~~~~~~~~~

* <<install, Installation>>
* Will man einfach Texte mit `asciidoc` Markup verfassen sollte man zum
  <<asciidoc-syntax, ASCIIdoc Syntax>> Abschnitt gehen oder zur Beschreibung
  der <<cmd-api, Kommandozeilenparameter>>.
** Alternativ findet man auch in der
   https://docs.asciidoctor.org/asciidoc/latest/[Aciidoc Language
   Documentation] vom asciidoctor Projekt eine hervorragende Übersicht.
** Dort gibt es auch eine
   https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[Quick
   Syntax Reference].

|
How-To Guides
~~~~~~~~~~~~~

|
Hintergrund Informationen
~~~~~~~~~~~~~~~~~~~~~~~~~

* Will man wissen wie das Programm funktioniert oder es anpassen kann man
  einfach weiterlesen.

|
Referenz
~~~~~~~~

* API https://docs.rs/asciidoctrine/latest/asciidoctrine/[documentation]

|===

== Übersicht
Dieses Programm ist im https://en.wikipedia.org/wiki/Literate_programming[literate programming] Stil geschrieben. Gie Grundidee ist eine ASCIIdoc Benutzeranleitung so umzuarbeiten, dass sie sich automatisch zu einem ausführbaren Programm mit Tests kompilieren lässt.

Dazu verwenden wir https://kober-systems.github.io/literate_programming_toolsuite/lisi/lisi.html[lisi] (welches im gleichen Repo verwaltet wird) als Werkzeug.

=== Motivation und Hintergrund
Das Programm http://jgm.github.io/lunamark/doc/lunamark.html[lunamark] hat
ursprünglich mein Interesse für http://www.lua.org[lua],
http://www.inf.puc-rio.br/~roberto/lpeg/[lpeg] und die Implementierung von
Parsern im Allgemeinen geweckt. Ich war begeistert wie der Eingabetext mit
Mustern abgesucht und umgewandelt wurde (vorher kannte ich nur
https://en.wikipedia.org/wiki/Regular_expression[regular expressions] und wäre
bei solch komplexen Aufgaben sofort an Grenzen gestoßen).

Ich fing an einen asciidoc parser für lunamark zu schreiben. Nach einiger Zeit
stellten sich ein paar Probleme heraus:

* lunamark ist für https://daringfireball.net/projects/markdown/[markdown]
  geschrieben und das ist nicht für beliebig komplexe Dokumente geeignet.
* Der Eingabetext wird sofort in das Ausgabeformat umgewandelt und nicht in
  einen https://en.wikipedia.org/wiki/Abstract_syntax_tree[AST].

Das zweite Problem ist in meinem Fall problematischer als das erste, da ich das Werkzeug nicht nur benutzen will um Dokumente zu erstellen. Hat man einen AST kann man nach belieben filtern, umsortieren, bearbeiten und in völlig andere Formate einbauen.

=== Programmarchitektur
Aus diesem Grund soll dieses Programm mehrschrittig vorgehen und alle Dateien
zunächst in einen AST umwandeln:

[[dataflow-outline]]
[ditaa]
.Module und Datenstrom in asciidoctrine
----

                         /-/-------------\                   /-/-----------\
                         | |             |                   | |           |
                         | | Steuerungs- +-=----+            | | Styles    +------+
                         | | dateien ... |      |            | | (css,...) |      |
                         \-\-------------/      |            \-\-----------/      |
                                                v                                 v
  /----------\   +--------+   /-----\   +---------------+   /-----\   +------------------+   /----------------\
  |          |   | {io}   |   |     |   | {io}          |   |     |   | {io}             |   |                |
  | Eingabe- +-->| Reader +-->| AST +-->| Erweiterungen +-->| AST +-->| Output Processor |-->| Ausgabedateien |
  | Datei    |   |        |   |     |   | ...           |   |     |   | (Writer)         |   | (html,pdf,...) |
  \----------/   +--------+   \-----/   +------+--+-----+   \-----/   +------------------+   \----------------/
                                 ^             |  :
                                 |     ...     |  |   /----------------\-\
                                 +-=-----------+  |   | optionale      | |
                                                  +-->| Ausgabedateien | |
                                                      | (png,svg,...)  | |
                                                      \----------------/-/

----

So kann man einerseits leicht unterschiedliche <<generate-output, Ausgabeformate>> unterstützen und andererseits eine <<api>> zur Verfügung stellen, die Zugriff auf die gesamte Dokumentstruktur gibt.

Der generelle Ablauf ist folgendermaßen:

Die Eingabedatei(en) wird(werden) eingelesen::
  * Diese wird von einem <<reader>> eingelesen und in einen AST umgewandelt.
  * Der <<reader>> wird nur einmal ausgewählt und ist (im Fall von mehreren
    Eingabedateien) für alle Eingabedateien gleich.
  * Das standardmäßige Eingabeformat ist <<asciidoc-syntax>>.
Der AST wird von einer oder mehreren Erweiterungen modifiziert::
  * Jede <<extensions, Erweiterung>> bekommt einen AST als Parameter übergeben
    und gibt einen AST zurück.
  * Erweiterungen können über die <<cmd-api, Kommandozeile>> oder die <<api>>
    weitere Parameter und Steuerungsdateien (von beliebigem Format) übergeben
    werden.
  * Es können beliebig viele Erweiterungen in beliebiger Reihenfolge
    hintereinander geschaltet werden.
  * Ob eine Erweiterung eigene Ausgabedateien erzeugt, bleibt ihr selbst
    überlassen.
  * Standardmäßig sind keine Erweiterungen aktiviert.
Ein Output Prozessor (Writer) wandelt den AST in eine Ausgabedatei um::
  * Der Writer kann über die <<cmd-api, Kommandozeile>> oder die <<api>> Parameter
    oder Styledateien (wie css-Stylesheets etc) übergeben bekommen.
  * Das standardmäßige Ausgabeformat ist <<html5>>.

== Implementierung
`asciidoctrine` ist ein rust Programm. Der Hauptteil des Programms ist in einer
Bibliothek implementiert. Ein kleiner Teil ist ein Kommandozeilenprogramm
welches diese Bibliothek benutzt und die Parameter übergibt.

[source, rust, save]
.src/lib.rs
----
<<crate_usages>>

<<internal_modules>>

<<public_structs>>

<<interfaces|join="\n\n">>
----

Die Bibliothek wiederum teilt den Großteil ihrer Aufgaben einigen abgetrennten
Modulen zu:

[[internal_modules]]
[source, rust]
.Module innerhalb des crates
----
mod ast;         // <1>
pub use ast::*;
pub mod cli_template;
pub mod options;
pub mod util;
pub mod extract_toc;
pub mod reader;
pub use reader::asciidoc::AsciidocReader;
pub use reader::json::JsonReader;
pub use reader::markdown::MarkdownReader;
mod writer;
pub use writer::html::HtmlWriter;
pub use writer::docx::DocxWriter;
pub use writer::json::JsonWriter;
pub use writer::asciidoc::AsciidocWriter;
----
<1> `ast` definiert das allgemeine Zwischenformat für alle Dokumente.

[[public_structs]]
[source, rust]
.Fehlerbehandlung
----
#[derive(Error, Debug)]
pub enum AsciidoctrineError {
  #[error("could not parse input")]
  Parse(#[from] pest::error::Error<reader::asciidoc::Rule>),
  #[error(transparent)]
  Json(#[from] serde_json::Error),
  #[error(transparent)]
  Io(#[from] std::io::Error),
  #[error(transparent)]
  BufWriter(#[from] io::IntoInnerError<io::BufWriter<Vec<u8>>>),
  #[error(transparent)]
  Template(#[from] tera::Error),
  #[error(transparent)]
  Utf8(#[from] std::str::Utf8Error),
  #[error(transparent)]
  Docx(#[from] docx_rs::DocxError),
  #[error("Child process stdin has not been captured!")]
  Childprocess,
  #[error("malformed ast structure")]
  MalformedAst,
}

type Result<T> = std::result::Result<T, AsciidoctrineError>;
----

[[crate_usages]]
[source, rust]
----
extern crate pest;
#[macro_use]
extern crate pest_derive;

use std::io;
use thiserror::Error;
----

[[input-format]]
=== Eingabeformate

[source, rust, save]
.src/reader/mod.rs
----
pub mod asciidoc;
pub mod json;
pub mod markdown;
----

:leveloffset: +3

[[asciidoc-syntax]]

include::asciidoc-syntax.adoc[]

include::src/json-syntax.adoc[]

= Json

[source, rust, save]
.src/reader/json.rs
----
pub use crate::ast::*;
use crate::options::Opts;
use crate::util::{Env};
use crate::Result;

pub struct JsonReader {}

impl JsonReader {
  pub fn new() -> Self {
    JsonReader {}
  }
}

impl crate::Reader for JsonReader {
  fn parse<'a>(&self, input: &'a str, _args: &Opts, _env: &mut Env) -> Result<AST<'a>> {
    let ast = serde_json::from_str(input)?;

    Ok(ast)
  }
}
----

:leveloffset: -3

[[output-format]]
=== Ausgabeformate
Der ganze Sinn des Programmes besteht darin, aus einer einzigen Datenquelle
verschiedene Ausgabedateien zu erzeugen. Diese können noch eigenen
Vorstellungen oder Vorgaben formatiert und abgelegt werden. `asciidoctrine`
unterstützt verschiedene Ausgabeformate, die in den folgenden Abschnitten
beschrieben werden (sowie wie man Formatierungsanpassungen vornehmen kann)

[source, rust, save]
.src/writer/mod.rs
----
pub mod html;
pub mod docx;
pub mod json;
pub mod asciidoc;
----

:leveloffset: +3

include::src/output/html5.adoc[]

[[html5]]
= Html5
Html ist _das_ Format für Webseiten.

include::src/output/docbook.adoc[]
include::src/output/manpage.adoc[]
include::src/output/pdf.adoc[]
include::src/output/json-ast.adoc[]

= Json

[source, rust, save]
.src/writer/json.rs
----
pub use crate::ast::*;
use crate::{options, Result};
use std::io;

pub struct JsonWriter {}

impl JsonWriter {
  pub fn new() -> Self {
    JsonWriter {}
  }
}

impl<T: io::Write> crate::Writer<T> for JsonWriter {
  fn write<'a>(&mut self, ast: AST, _args: &options::Opts, mut out: T) -> Result<()> {
    out.write_all(serde_json::to_string_pretty(&ast)?.as_bytes())?;
    out.flush()?;

    Ok(())
  }
}
----

:leveloffset: -3

== asciidoctrine in andere Programme einbinden
TODO

[[cmd-api]]
=== Aufruf auf der Kommandozeile
Der einfachste Weg asciidoctrine in ein anderes Programm einzubinden ist es über der Kommandozeile aufzurufen.

[source, rust, save]
.src/options.rs
----
use clap::{Parser, ValueEnum};
use std::path::PathBuf;

/// Parse a single key-value pair
fn parse_key_val<T, U>(s: &str) -> Result<(T, U), String>
where
  T: std::str::FromStr,
  U: std::str::FromStr,
{
  let pos = s
    .find('=')
    .ok_or_else(|| format!("invalid KEY=value: no `=` found in `{}`", s))?;
  let key = s[..pos]
    .parse()
    .or_else(|_| Err(format!("couldn't parse key in `{}`", s)))?;
  let value = s[pos + 1..]
    .parse()
    .or_else(|_| Err(format!("couldn't parse value in `{}`", s)))?;
  Ok((key, value))
}

#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, ValueEnum, Debug)]
pub enum Reader {
  Asciidoc,
  Markdown,
  Json,
}

#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, ValueEnum, Debug)]
pub enum Writer {
  Html5,
  Docbook,
  Pdf,
  Json,
  Docx,
  // The asciidoc output makes it possible
  // to use this tool as a preprocessor for
  // other asciidoc tools while it is maturing
  Asciidoc,
}

#[derive(Parser, Debug)]
#[clap(author, version, about, long_about = None)]
pub struct Opts {
  #[clap(short = 'r', long = "reader-format", default_value_t = Reader::Asciidoc)]
  #[clap(value_enum)]
  pub readerfmt: Reader,
  #[clap(short = 'w', long = "writer-format", default_value_t = Writer::Html5)]
  #[clap(value_enum)]
  pub writerfmt: Writer,
  #[clap(long)]
  pub dry_run: bool,
  #[clap(short = 'e', long = "extension")]
  pub extensions: Vec<String>,
  #[clap(long)]
  pub template: Option<PathBuf>,
  #[clap(long)]
  pub stylesheet: Option<PathBuf>,
  #[clap(short = 'a', long = "attribute")]
  #[clap(value_parser = parse_key_val::<String, String>, number_of_values = 1)]
  defines: Vec<(String, String)>,
  #[clap(name = "FILE")]
  pub input: Option<PathBuf>,
  #[clap(short = 'o')]
  pub output: Option<PathBuf>,
}

pub fn from_args() -> Opts {
  Opts::parse()
}
----

[[extensions]]
== asciidoctrine erweitern
Man kann `asciidoctrine` über eine api Schnittstelle erweitern. Dazu werden für alle wichtigen Funktionen Schnittstellen definiert, welche von der jeweiligen Erweiterung implementiert werden müssen.

[[reader]]
=== Neue Datenformate einlesen
Jedes Eingabeformat muss zunächst in einen <<ast, Abstract Syntax Tree>> ungewandelt werden um von asciidoctrine verarebitet werden zu können. Auch alle intern unterstützten Dateiformate implementieren die gleiche Schnittstelle.

[[interfaces]]
[source, rust]
----
pub trait Reader {
  fn parse<'a>(&self, input: &'a str, args: &options::Opts, env: &mut util::Env) -> Result<AST<'a>>;
}
----

[[extension]]
=== Den AST verarbeiten/modifizieren
Manchmal will man den <<ast, Abstract Syntax Tree>> verarbeiten und daraus Informationen nutzen (<<../lisi.adoc#, lisi>> verwendet ihn z.B. um daraus Quelltext-Dateien zu extrahieren). Das ermöglicht sehr viele Anwendungsfälle:

* Daten extrahieren und Prüfungen oder Statistiken damit durchführen
* Rechtschreibprüfung durchführen
* Mehrere Dokumente vereinen
* etc

Für alle diese Funktionen definieren wir eine Schnittstelle welche einen AST einließt und am Ende einen AST ausgibt. Wie er zwischendurch verarbeitet wird und ob er modifiziert wird bleibt vollständig der Erweiterung überlassen.

[[interfaces]]
[source, rust]
----
pub trait Extension {
  // TODO Options (Kann auch über Attributes in AST gemacht werden)
  fn transform<'a>(&mut self, input: AST<'a>) -> anyhow::Result<AST<'a>>;
}
----

[[writer]]
=== Neue Ausgabeformate unterstützen
Um ein weiteres Ausgabeformat zu implementieren muss die entsprechende Schnittstelle implementiert werden. Sie konsumiert einen <<ast, AST>> und ist dafür verantwortlich eine Datei zu erstellen, welche das Ausgabeformat verwendet.

[[interfaces]]
[source, rust]
----
pub trait Writer<T: io::Write> {
  // TODO Result zurückgeben mit Fehler oder Liste der Geschriebenen Dateien
  fn write<'a>(&mut self, ast: AST, args: &options::Opts, out: T) -> Result<()>;
}
----

[[ast]]
=== Der Abstract Syntax Tree
Alle Schnittstellen basieren auf der gleichen Datenstrucktur. Diese bildet ein Dokument vollständig ab.

[source, rust, save]
.src/ast.rs
----
use std::{fmt::Debug, marker::PhantomPinned, pin::Pin, ptr::NonNull};
use serde::{Deserialize, Deserializer, Serialize};
use crate::util::Env;

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct AST<'a> {
  pub content: &'a str,
  pub elements: Vec<ElementSpan<'a>>,
  pub attributes: Vec<Attribute<'a>>,
}

<<ast_structs>>
----

[[ast_structs]]
[source, rust]
----
impl AST<'_> {
  pub fn get_attribute(&self, name: &str) -> Option<&str> {
    for attribute in self.attributes.iter() {
      if &attribute.key == name {
        return match &attribute.value {
          AttributeValue::Ref(value) => Some(value),
          AttributeValue::String(value) => Some(value.as_str()),
        };
      }
    }

    None
  }
}

impl Default for AST<'_> {
  fn default() -> Self {
    Self {
      content: "",
      elements: vec![],
      attributes: vec![],
    }
  }
}

/// The basic element of a document
///
/// This is meant to form a tree of document element.
/// Every element holds references to its source, it
/// subelements and the attributes defined on it.
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct ElementSpan<'a> {
  // The source document. Could be empty if
  // e.g. it's the same as the source of it's
  // parent
  pub source: Option<String>,
  // A string reference to the source
  pub content: &'a str,
  // TODO Add start and end point
  pub start: usize,
  pub end: usize,
  /// We count the lines for usage in other tools
  pub start_line: usize,
  pub start_col: usize,
  pub end_line: usize,
  pub end_col: usize,

  pub element: Element<'a>,
  /// The subelements of a nodes
  pub children: Vec<ElementSpan<'a>>,
  /// The attributes applying to that node and
  /// all children
  pub positional_attributes: Vec<AttributeValue<'a>>,
  /// The attributes applying to that node and
  /// all children
  pub attributes: Vec<Attribute<'a>>,
}

impl<'a> ElementSpan<'a> {
  pub fn get_attribute(&self, name: &str) -> Option<&str> {
    for attribute in self.attributes.iter() {
      if &attribute.key == name {
        return match &attribute.value {
          AttributeValue::Ref(value) => Some(value),
          AttributeValue::String(value) => Some(value.as_str()),
        };
      }
    }

    None
  }

  pub fn add_offset(self, other: &ElementSpan<'_>) -> Self {
    let mut base = self;

    base.start += other.start;
    base.end += other.start;
    base.start_line += other.start_line - 1;
    base.end_line += other.start_line - 1;
    base.start_col += other.start_col - 1;
    base.end_col += other.start_col - 1;

    base
  }

  pub fn element(self, e: Element<'a>) -> Self {
    let mut base = self;

    base.element = e;
    base
  }

  pub fn error(self, msg: &str) -> Self {
    self.element(Element::Error(msg.to_string()))
  }

  pub fn add_attribute(self, a: Attribute<'a>) -> Self {
    let mut base = self;

    base.attributes.push(a);
    base
  }

  pub fn add_positional_attribute(self, a: AttributeValue<'a>) -> Self {
    let mut base = self;

    base.positional_attributes.push(a);
    base
  }

  pub fn add_child(self, e: ElementSpan<'a>) -> Self {
    let mut base = self;

    base.children.push(e);
    base
  }
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub enum Element<'a> {
  Attribute(#[serde(borrow)] Attribute<'a>),
  /// A section of ignored text
  Comment,
  /// A text paragraph
  Paragraph,
  /// A header section
  Title {
    level: u32,
  },
  Table,
  List(ListType),
  Image,
  Anchor,
  /// Holds all blocks with special content and the type
  /// TODO Could be done with ExternalContent and all known
  /// Types here direktly
  TypedBlock {
    kind: BlockType,
  },
  /// Holds content which is not prozessed direktly by
  /// asciidoctrine. It can be anything. Outputs or
  /// postprocessors could use or ignore it at their
  /// will (e.g. videos)
  ExternalContent,
  /// Holds a reference to the include statement
  /// and a document inside
  IncludeElement(IncludeElement<'a>),

  /// The following variants are inline elements nested
  /// inside a conainer element

  /// Element with a special style. The attributes define the kind of style
  Styled,
  /// A chunk of text.
  Text,
  /// An internal reference or link
  XRef,
  /// An external link
  Link,
  /// A list item
  ListItem(u32),
  /// A table row
  TableRow,
  /// A table cell
  TableCell,
  /// A wrong formatted text or block
  Error(String),
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub enum ListType {
  Bullet,
  Number,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub enum BlockType {
  Comment,
  Passtrough,
  Listing,
  Literal,
  Sidebar,
  Quote,
  Example,
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub enum AttributeValue<'a> {
  String(String),
  Ref(&'a str),
}

impl AttributeValue<'_> {
  pub fn as_str(&self) -> &str {
    match self {
      AttributeValue::Ref(value) => value,
      AttributeValue::String(value) => value.as_str(),
    }
  }
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct Attribute<'a> {
  pub key: String,
  #[serde(borrow)]
  pub value: AttributeValue<'a>,
}

#[derive(Clone)]
struct UnmovableString {
  pub content: String,
  pub content_ref: NonNull<str>,
  _pin: PhantomPinned,
}

impl PartialEq for UnmovableString {
  fn eq(&self, other: &Self) -> bool {
    self.content == other.content
  }
}

impl Debug for UnmovableString {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    write!(f, "UnmovableString(\"{}\")", self.content)
  }
}

impl UnmovableString {
  fn new(content: String) -> Pin<Box<Self>> {
    let res = Self {
      content,
      content_ref: "".into(),
      _pin: PhantomPinned,
    };
    let mut boxed = Box::new(res);
    boxed.content_ref = NonNull::from(boxed.content.as_str());
    let pin = Box::into_pin(boxed);
    pin
  }
}

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct IncludeElement<'a> {
  #[serde(
    serialize_with = "serialize_unmovable_string",
    deserialize_with = "deserialize_unmovable_string"
  )]
  content: Pin<Box<UnmovableString>>,
  #[serde(borrow)]
  pub inner: AST<'a>,
  #[serde(skip)]
  _pin: PhantomPinned,
}

impl IncludeElement<'_> {
  pub fn from_parser(
    content: String,
    env: &mut Env,
    parser: &dyn for<'a> Fn(&'a str, &mut Env) -> Result<AST<'a>, String>,
  ) -> Result<Self, String> {
    let content = UnmovableString::new(content);
    let content_ref = unsafe { content.content_ref.as_ref() };
    let inner_ast = parser(content_ref, env)?;

    Ok(IncludeElement {
      content,
      inner: inner_ast,
      _pin: PhantomPinned,
    })
  }

  pub fn from_data(content: String, inner: AST<'static>) -> Self {
    IncludeElement {
      content: UnmovableString::new(content),
      inner,
      _pin: PhantomPinned,
    }
  }
}

fn serialize_unmovable_string<S>(
  string: &Pin<Box<UnmovableString>>,
  serializer: S,
) -> Result<S::Ok, S::Error>
where
  S: serde::Serializer,
{
  serializer.serialize_str(&string.content)
}

fn deserialize_unmovable_string<'de, D>(
  deserializer: D,
) -> Result<Pin<Box<UnmovableString>>, D::Error>
where
  D: Deserializer<'de>,
{
  let string = String::deserialize(deserializer)?;
  Ok(UnmovableString::new(string))
}
----

Jedes Dokument ist im Großen und Ganzen eine Ansammlung von hintereinander liegenden Strukturelementen (wie Überschriften, Texten, etc). In unserem Fall hat ein Dokument zusätzlich noch Eigenschaften welche ihm zugewiesen werden können.

== tmp Implementierung

[%collapsible]
====

Im Fehlerfall ist es nicht immer gut gleich das Programm zu beenden. Damit der Benutzer dennoch darauf reagieren kann geben wir bei Bedarf log-Meldungen aus. Dazu benötigen wir den entspechenden Crate.

[[crate_usages]]
[source, rust]
----
#[macro_use]
extern crate log;
----

[source, rust, save]
.src/util.rs
----
use std::collections::HashMap;
use std::fs;
use std::io::{self, ErrorKind, Write};
use std::path::Path;
use std::process::{Command, Stdio};

pub trait Environment {
  fn read_to_string(&mut self, path: &str) -> crate::Result<String>;
  fn write(&mut self, path: &str, content: &str) -> crate::Result<()>;
  fn eval(&mut self, interpreter: &str, content: &str) -> crate::Result<(bool, String, String)>; // success, Stdout, Stderr
}

pub struct Io {}

impl Io {
  pub fn new() -> Self {
    Io {}
  }
}

fn fs_read_to_string(path: &str) -> crate::Result<String> {
  Ok(fs::read_to_string(path)?)
}

impl Environment for Io {
  fn read_to_string(&mut self, path: &str) -> crate::Result<String> {
    fs_read_to_string(path)
  }

  fn write(&mut self, path: &str, content: &str) -> crate::Result<()> {
    let path = Path::new(path);
    if let Some(path) = path.parent() {
      if !path.exists() {
        fs::create_dir_all(path)?;
      }
    }

    if path.exists() {
      let old_content = fs::read_to_string(path)?;
      if old_content == content {
        return Ok(());
      }
    }
    fs::write(path, content)?;

    Ok(())
  }

  fn eval(&mut self, interpreter: &str, content: &str) -> crate::Result<(bool, String, String)> {
    let mut eval = Command::new(interpreter)
      .stdin(Stdio::piped())
      .stderr(Stdio::piped())
      .stdout(Stdio::piped())
      .spawn()?;

    eval
      .stdin
      .as_mut()
      .ok_or(crate::AsciidoctrineError::Childprocess)?
      .write_all(content.as_bytes())?; // TODO Wie soll EOF gesendet werden?
    let output = eval.wait_with_output()?;

    let success = output.status.success();
    let out = match String::from_utf8(output.stdout) {
      Ok(out) => out,
      Err(_) => "Error: Couldn't decode stdout".to_string(),
    };
    let err = match String::from_utf8(output.stderr) {
      Ok(out) => out,
      Err(_) => "Error: Couldn't decode stderr".to_string(),
    };

    Ok((success, out, err))
  }
}

pub struct EvalData {
  success: bool,
  out: String,
  err: String,
  add_files: Vec<(String, String)>,
  remove_files: Vec<String>,
}

pub struct Cache {
  files: HashMap<String, String>,
  evaluations: HashMap<(String, String), EvalData>,
}

impl Cache {
  pub fn new() -> Self {
    Cache {
      files: HashMap::default(),
      evaluations: HashMap::default(),
    }
  }

  pub fn get_files(self) -> HashMap<String, String> {
    self.files
  }
}

impl Environment for Cache {
  fn read_to_string(&mut self, path: &str) -> crate::Result<String> {
    Ok(self.files.remove(path).ok_or(io::Error::new(
      ErrorKind::NotFound,
      "file not found in cache",
    ))?)
  }

  fn write(&mut self, path: &str, content: &str) -> crate::Result<()> {
    self.files.insert(path.to_string(), content.to_string());

    Ok(())
  }

  fn eval(&mut self, interpreter: &str, content: &str) -> crate::Result<(bool, String, String)> {
    match self
      .evaluations
      .remove(&(interpreter.to_string(), content.to_string()))
    {
      Some(EvalData {
        success,
        out,
        err,
        add_files,
        remove_files,
      }) => {
        for path in remove_files.iter() {
          self.files.remove(path);
        }
        for (path, content) in add_files.into_iter() {
          self.files.insert(path, content);
        }
        Ok((success, out, err))
      }
      None => Err(crate::AsciidoctrineError::Childprocess),
    }
  }
}

pub struct FakeOutput {
  files: HashMap<String, String>,
}

impl FakeOutput {
  pub fn new() -> Self {
    Self {
      files: HashMap::default(),
    }
  }

  pub fn get_files(self) -> HashMap<String, String> {
    self.files
  }
}

impl Environment for FakeOutput {
  fn read_to_string(&mut self, path: &str) -> crate::Result<String> {
    fs_read_to_string(path)
  }

  fn write(&mut self, path: &str, content: &str) -> crate::Result<()> {
    let real_path = Path::new(path);
    if real_path.exists() {
      let old_content = fs::read_to_string(real_path)?;
      if old_content == content {
        return Ok(());
      }
    }

    self.files.insert(path.to_string(), content.to_string());

    Ok(())
  }

  fn eval(&mut self, _interpreter: &str, _content: &str) -> crate::Result<(bool, String, String)> {
    error!("eval not supported in fake output");
    Err(crate::AsciidoctrineError::Childprocess)
  }
}

pub enum Env {
  Io(Io),
  Cache(Cache),
  FakeOutput(FakeOutput),
}

impl Env {
  pub fn get_cache(self) -> Option<HashMap<String, String>> {
    match self {
      Env::Io(_) => None,
      Env::Cache(env) => Some(env.get_files()),
      Env::FakeOutput(env) => Some(env.get_files()),
    }
  }
}

impl Environment for Env {
  fn read_to_string(&mut self, path: &str) -> crate::Result<String> {
    match self {
      Env::Io(env) => env.read_to_string(path),
      Env::Cache(env) => env.read_to_string(path),
      Env::FakeOutput(env) => env.read_to_string(path),
    }
  }

  fn write(&mut self, path: &str, content: &str) -> crate::Result<()> {
    match self {
      Env::Io(env) => env.write(path, content),
      Env::Cache(env) => env.write(path, content),
      Env::FakeOutput(env) => env.write(path, content),
    }
  }

  fn eval(&mut self, interpreter: &str, content: &str) -> crate::Result<(bool, String, String)> {
    match self {
      Env::Io(env) => env.eval(interpreter, content),
      Env::Cache(env) => env.eval(interpreter, content),
      Env::FakeOutput(env) => env.eval(interpreter, content),
    }
  }
}
----

====

[[install]]
== Installation
To install directly from the sources you will need to have
https://doc.rust-lang.org/cargo/getting-started/installation.html[cargo]
installed first.

After that run

[source, sh]
----
cargo install asciidoctrine
----

from the command line.

== Build
TODO

== Tests

=== Testumgebung
Um `asciidoctrine` zu testen verwenden wir die im Userguide
beschriebenen Beispiele.

Der generelle Aufbau eines Tests ist:

[[unit-test-template]]
[source, rust]
.Grundlegender Aufbau eines Unit Tests
----
#[test]
fn {test_name}() -> Result<()> {
  let content = r#"{asciidoc_content}"#;
  let reader = AsciidocReader::new();
  let opts = options::Opts::parse_from(vec!["asciidoctrine", "--template", "-"]);
  let mut env = util::Env::Cache(util::Cache::new());
  {add_inputs}
  let ast = reader.parse(content, &opts, &mut env)?;

  let mut buf = BufWriter::new(Vec::new());
  let mut writer = HtmlWriter::new();
  writer.write(ast, &opts, &mut buf)?;

  let output = String::from_utf8(buf.into_inner()?)?;
  assert_eq!(
    output,
    r#"{expected_content}"#
  );

  Ok(())
}
----

Anschließend packen wir alle Tests in eine Datei:

[source, rust, save]
.tests/asciidoc_to_html_test.rs
----
use anyhow::Result;
use asciidoctrine::{self, *};
use asciidoctrine::util::Environment;
use clap::Parser;
use pretty_assertions::assert_eq;
use std::io::BufWriter;

<<html-unit-tests>>
----

Manchmal haben die Tests mehr als eine Eingangs-Datei. Alle Dateien
welche auf dem Dateisystem bereits vorhanden sein müssten können wir
folgendermaßen hinzufügen.

[[unit-test-add-in-file-template]]
[source, rust]
----
env.write("{filepath}", r#"{content}"#)?;
----

Um die Tests zu erzeugen gehen wir alle Beispiele im Userguide durch,
welche mit entsprechenden Attributen gekennzeichnet wurden.

[[html-unit-tests]]
[source, js, pipe]
----
let template = lisi.get_snippet("unit-test-template").content;
let add_input_template = lisi.get_snippet("unit-test-add-in-file-template").content;
let tests = "";

fn split(input, seperator) {
  let out = [];
  let start = 0;
  let idx = input.index_of(seperator);
  while idx > -1 {
    let chunk = input.sub_string(start, idx - start);
    out.push(chunk);

    start = idx + 1;
    idx = input.index_of(seperator, start);
  };
  out.push(input.sub_string(start));
  return out;
}

for name in lisi.get_snippet_names() {
  if name.contains("unittest_") && name.contains("_input") {
    let out_template = template;
    let add_inputs = "";

    let snippet = lisi.get_snippet(name);
    out_template.replace("{test_name}", snippet.attrs.name);
    let asciidoc_content = "\n" + snippet.content + "\n";
    asciidoc_content.replace(" -- <1>", "");
    asciidoc_content.replace(" -- <2>", "");
    out_template.replace("{asciidoc_content}", asciidoc_content);

    if "inputs" in snippet.attrs {
      let input_names = snippet.attrs.inputs;
      for input_name in split(input_names, ",") {
        let input_template = add_input_template;
        let input_snippet = lisi.get_snippet(input_name);
        input_template.replace("{content}", input_snippet.content);
        input_template.replace("{filepath}", input_snippet.attrs.title);
        add_inputs += input_template;
      }
    }
    out_template.replace("{add_inputs}", add_inputs);

    let output_snippet = lisi.get_snippet(snippet.attrs.output);
    out_template.replace("{expected_content}", output_snippet.content + "\n");

    tests += out_template;
    tests += "\n\n";
  }
}

lisi.store("html-unit-tests", tests);
----

== Verwandte Projekte
Es gibt einige Projekte mit vergleichbaren Zielen und teilweise auch einer vergleichbaren Architektur wie asciidoctrine.

* asciidoc TODO
* http://asciidoctor.org[asciidoctor] ist der Standard um asciidoc Dokumente zu rendern. Es ist in ruby geschrieben. Da der interne AST aber nicht direkt manipulierbar ist (obwohl es natürlich Möglichkeiten für Erweiterungen und auch viele tolle Plugins gibt) scheint es mir nicht ganz so flexibel wie asciidoctrine zu sein.
* http://jgm.github.io/lunamark/doc/lunamark.html[lunamark] wurde ja bereits in der Einleitung erwähnt. Es war eine große Quelle der Inspiration für dieses Projekt.
* https://pandoc.org/[Pandoc] ist ein Projekt mit einem sehr ähnlichen Aufbau. Es ist eine großartige Software und kommt vom gleichen Autor wie lunamark. Es wurde in Haskell geschrieben. Der große Unterschied (und auch der Grund, warum ich die Ziele von asciidoctrine nicht damit erreichen kann) ist, dass es einen https://hackage.haskell.org/package/pandoc-types/docs/Text-Pandoc-Definition.html[simpleren AST] benutzt (denn die Ausgangssprache ist hier Markdown). Daher kann es einiges nicht abbilden was ich gerne in Dokumenten verwende.

