[package]
name = "ansicht"
version = "0.1.0"
authors = ["Benjamin Kober <benko@kober-systems.com>"]
edition = "2018"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
thiserror = "2.0"
log = "0.4.8"

[dev-dependencies]
pretty_assertions = "1"
