= Release process

[source, sh, eval]
----
<<check_vcs_is_clean>>

<<generate_sources>>

<<generate_websites>>

<<build_and_test>>

<<semver_testing>>
<<check_maturity_level_in_readme>>

<<publish_on_github>>

<<publish_on_crates_io>>
----

== Prerequisites
There must be some programms installed on your computer to release a version of
the `literate programming toolsuite`.

git:: It is currently published on github so we need git.
rust, cargo, etc:: These porgramms are written in rust therefore we need the
  rust toolchain.
lisa:: `lisa` is bootstraped so we need it installed on our computer.
asciidoctor:: Right now we need `asciidcotor` to build the docs. In future
  versions it is planned to use our own `asciidoctrine` programm. There are some
  additional dependencies for our doc generation process.
asciidcotor-diagram::: For our diagrams.
ditaa::: For our diagrams.
pygments::: For source code highlighting.

== Check if generated files are untouched in VCS
TODO

== Generate source files

[[generate_sources]]
[source, sh]
----
echo "Start generating source files ..."

cd lisa
lisa lisa.adoc
# The new generated source must be able to
# generate itself
cargo run --manifest-path ../Cargo.toml -- lisa.adoc || exit 1
# TODO check if version generated by the old compiler and by the new compiler
#      are equal
cd ..

echo "Generating source files done!"

----

== Build and test

[[build_and_test]]
[source, sh]
----
cargo test || exit 1

----

== Build websites for github pages
TODO later we want to do this with `asciidoctrine` alone.

[[generate_websites]]
[source, sh]
----
echo "Start generating html files ..."

asciidoctor -r asciidoctor-diagram \
            -D build/html \
            -a source-highlighter=pygments \
            -a toc=left \
            -a icons=font \
            lisa/lisa.adoc
asciidoctor -r asciidoctor-diagram \
            -D build/html \
            -a source-highlighter=pygments \
            -a toc=left \
            -a icons=font \
            asciidoctrine/asciidoctrine.adoc

echo "Generating html files done!"

----

== Publish sources to github
TODO

== Publish to crates.io
TODO
