= Release process

[source, sh, eval]
----
<<check_vcs_is_clean>>

<<generate_sources>>
<<check_vcs_is_clean>>

<<generate_websites>>
<<check_vcs_is_clean>>

<<build_and_test>>

<<semver_testing>>
<<check_maturity_level_in_readme>>

<<publish_on_github>>

<<publish_on_crates_io>>
----

== Prerequisites
There must be some programms installed on your computer to release a version of
the `literate programming toolsuite`.

git:: It is currently published on github so we need git.
rust, cargo, etc:: These porgramms are written in rust therefore we need the
  rust toolchain.
asciidoctor:: Right now we need `asciidcotor` to build the docs. In future
  versions it is planned to use our own `asciidoctrine` programm. There are some
  additional dependencies for our doc generation process.
asciidcotor-diagram::: For our diagrams.
ditaa::: For our diagrams.
pygments::: For source code highlighting.

== Check if files are untouched in VCS
For a new release we expect the repo to be clean. Every time the source
generates itself it should stay the same as well.

[[check_vcs_is_clean]]
[source, sh]
----
if [[ `git status --porcelain` ]]; then
  echo "Git repo has changes. Please commit before release." 1>&2
  exit 1
fi
----

== Generate source files

[[generate_sources]]
[source, sh]
----
echo "Start generating source files ..."

cd lisa
# The new generated source must be able to
# generate itself
cargo run --manifest-path ../Cargo.toml -- lisa.adoc || exit 1
cd ..

echo "Generating source files done!"
----

== Build and test

[[build_and_test]]
[source, sh]
----
cargo test || exit 1
----

== Build websites for github pages
TODO later we want to do this with `asciidoctrine` alone.

[[generate_websites]]
[source, sh]
----
echo "Start generating html files ..."

asciidoctor -r asciidoctor-diagram \
            -D docs \
            -a source-highlighter=pygments \
            -a toc=left \
            -a icons=font \
            README.adoc -o index.html
asciidoctor -r asciidoctor-diagram \
            -D docs/lisa \
            -a source-highlighter=pygments \
            -a toc=left \
            -a icons=font \
            lisa/lisa.adoc
asciidoctor -r asciidoctor-diagram \
            -D docs/asciidoctrine \
            -a source-highlighter=pygments \
            -a toc=left \
            -a icons=font \
            asciidoctrine/asciidoctrine.adoc

echo "Generating html files done!"

----

== Publish sources to github
TODO

== Publish to crates.io
TODO
