name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
          - build: windows
            os: windows-latest
            rust: stable


    steps:
    - uses: actions/checkout@v5
    - name: Install Rust (rustup)
      run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Create artifact directory
      run: mkdir -p artifacts/${{ runner.os }}
    - name: Create archive for Windows
      run: cp ./target/release/lisi.exe ./artifacts/${{ runner.os }}/
      if: matrix.os == 'windows-latest'
    - uses: actions/upload-artifact@v4
      with:
        name: lisi-${{ runner.os }}
        path: ./artifacts/${{ runner.os }}
